server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Redirect all routes to index.html so React can handle client-side routing
    location / {
        try_files $uri $uri/ /index.html;
    }
}
