"""
Summarization router — POST /api/v1/genai/summarize.

This is the FastAPI equivalent of a Spring @RestController.
It handles HTTP concerns (validation, error responses) and
delegates business logic to the summarizer service.
"""

import logging

from fastapi import APIRouter, Depends, HTTPException

from app.schemas.summarize import SummarizeRequest, SummarizeResponse
from app.security import require_internal_service
from app.services.output_sanitizer import InvalidLlmOutputError
from app.services.summarizer import summarize

logger = logging.getLogger(__name__)

router = APIRouter(
    prefix="/api/v1/genai",
    tags=["GenAI"],
    dependencies=[Depends(require_internal_service)],
)


@router.post(
    "/summarize",
    response_model=SummarizeResponse,
    summary="Summarize post content",
    description=(
        "Accepts post content (and optional title) and returns a 3-bullet summary "
        "generated by an LLM. The summary highlights the most important facts, "
        "findings, or takeaways from the post."
    ),
    responses={
        200: {"description": "Successfully generated summary"},
        422: {"description": "Invalid request or unusable sanitized LLM output"},
        502: {"description": "LLM service unavailable or returned an error"},
    },
)
async def summarize_post(request: SummarizeRequest) -> SummarizeResponse:
    """
    Summarize a post's content into 3 bullet points.

    This endpoint is called by the Content Service when a user
    clicks "Generate Summary" on a post detail page.
    """
    try:
        result = await summarize(request)
        return result
    except InvalidLlmOutputError as e:
        logger.warning("Post AI Summary output invalid after retry: %s", e)
        raise HTTPException(
            status_code=422,
            detail={
                "error": "invalid_llm_output",
                "message": "LLM returned unusable summary prose after retry.",
                "details": str(e),
            },
        )
    except Exception as e:
        logger.error("Summarization failed: %s", str(e), exc_info=True)
        raise HTTPException(
            status_code=502,
            detail={
                "error": "llm_error",
                "message": "Failed to generate summary. The LLM service may be unavailable.",
                "details": str(e),
            },
        )
