global:
  registry: ghcr.io/aet-devops26/team-colleague-md
  imagePullSecrets: []

services:
  user:
    image: user-service
    tag: latest
    port: 8081
    db:
      name: verita_users
      user: verita_user
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  content:
    image: content-service
    tag: latest
    port: 8082
    db:
      name: verita_content
      user: verita_user
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  recommendation:
    image: recommendation-service
    tag: latest
    port: 8083
    db:
      name: verita_recommendations
      user: verita_user
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  genai:
    image: genai-service
    tag: latest
    port: 8000
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"

  frontend:
    image: frontend
    tag: latest
    port: 80
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"

ingress:
  enabled: true
  host: verita.stud.k8s.aet.cit.tum.de
  clusterIssuer: letsencrypt-staging
  tls:
    secretName: verita-tls

user-postgresql:
  enabled: true
  auth:
    username: verita_user
    database: verita_users

content-postgresql:
  enabled: true
  auth:
    username: verita_user
    database: verita_content

recommendation-postgresql:
  enabled: true
  auth:
    username: verita_user
    database: verita_recommendations
