services:
  user:
    tag: dev
    resources:
      requests: { cpu: "100m", memory: "256Mi" }
      limits: { cpu: "300m", memory: "512Mi" }
  content:
    tag: dev
    resources:
      requests: { cpu: "100m", memory: "256Mi" }
      limits: { cpu: "300m", memory: "512Mi" }
  recommendation:
    tag: dev
    resources:
      requests: { cpu: "100m", memory: "256Mi" }
      limits: { cpu: "300m", memory: "512Mi" }
  genai:
    tag: dev
    resources:
      requests: { cpu: "50m", memory: "128Mi" }
      limits: { cpu: "200m", memory: "256Mi" }
  frontend:
    tag: dev
    resources:
      requests: { cpu: "50m", memory: "64Mi" }
      limits: { cpu: "100m", memory: "128Mi" }

ingress:
  host: dev.verita.stud.k8s.aet.cit.tum.de
