apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "verita.fullname" . }}-ingress
  labels:
    {{- include "verita.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-%s" .Release.Name "user" }}
                port:
                  number: {{ .Values.user.service.port }}
          - path: /content
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-%s" .Release.Name "content" }}
                port:
                  number: {{ .Values.content.service.port }}
          - path: /recommendation
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-%s" .Release.Name "recommendation" }}
                port:
                  number: {{ .Values.recommendation.service.port }}
          - path: /genai
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-%s" .Release.Name "genai" }}
                port:
                  number: {{ .Values.genai.service.port }}
          - path: /summarization
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-%s" .Release.Name "genai" }}
                port:
                  number: {{ .Values.genai.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-%s" .Release.Name "frontend" }}
                port:
                  number: {{ .Values.frontend.service.port }}
