apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-genai-llm
  labels:
    helm.sh/chart: {{ include "verita.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  nvidiaNimApiKey: {{ .Values.services.genai.llm.nvidiaNimApiKey | quote }}
  logosApiKey: {{ .Values.services.genai.llm.logosApiKey | quote }}
  gnewsApiKey: {{ .Values.services.genai.llm.gnewsApiKey | quote }}
