import { test, expect, type Page } from '@playwright/test';
import { loginAs, postCards, unique } from './support';

/**
 * US: Post Detail — read, engage, discuss.
 *
 * The AI summary is the product's differentiator, so it gets a test of its own: it is generated by
 * GenAI and served through content-service, which no unit test can stand in for.
 */

/** Opens the first seeded feed post in the reader. */
async function openFirstPost(page: Page) {
  await page.goto('/');
  await postCards(page).first().click();
  await expect(page).toHaveURL(/\/post\/[0-9a-f-]{36}$/);
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible();
}

test('POST-1: a reader can open a post and expand its AI summary', async ({ page }) => {
  await page.goto('/');
  // Seeded posts carry a COMPLETED summary; the panel renders nothing for the other states, so
  // find a post that actually has one rather than assuming the first card does.
  const cards = postCards(page);
  const summaryToggle = page.getByRole('button', { name: 'AI summary' });

  for (let i = 0; i < 5; i++) {
    await cards.nth(i).click();
    await expect(page).toHaveURL(/\/post\/[0-9a-f-]{36}$/);
    await expect(page.getByRole('heading', { level: 1 })).toBeVisible();
    if (await summaryToggle.isVisible()) break;
    await page.goto('/');
  }

  await expect(summaryToggle).toBeVisible();
  await summaryToggle.click();

  await expect(summaryToggle).toHaveAttribute('aria-expanded', 'true');
  await expect(page.getByText('Key points')).toBeVisible();
});

test('POST-2: liking and bookmarking a post persists to the reader', async ({ page }) => {
  await loginAs(page);
  await openFirstPost(page);

  const bookmark = page.getByRole('button', { name: 'Save' });
  const wasSaved = (await bookmark.getAttribute('aria-pressed')) === 'true';

  await bookmark.click();
  await expect(page.getByText(wasSaved ? 'Removed from bookmarks' : 'Saved to bookmarks')).toBeVisible();

  await page.getByRole('button', { name: 'Like' }).click();

  // A reload proves the writes reached content-service rather than only the optimistic UI. The
  // reader only knows what *this user* saved once the session is back, so wait for that first —
  // otherwise a slow restore reads as an unsaved post.
  await page.reload();
  await expect(page.locator('[data-testid="sidebar-signin"]')).toBeHidden();
  await expect(bookmark).toHaveAttribute('aria-pressed', String(!wasSaved));
});

test('POST-3: a signed-in reader can comment and see it in the thread', async ({ page }) => {
  await loginAs(page);
  await openFirstPost(page);

  const body = unique('E2E comment');
  // The composer starts collapsed to a placeholder and expands into a textarea on click.
  await page.getByText('Write a comment…').click();
  await page.getByPlaceholder('Write a comment…').fill(body);
  await page.getByRole('button', { name: 'Comment', exact: true }).click();

  // Scoped to the thread: the composer keeps the text too, so an unscoped match is ambiguous.
  const thread = page.locator('#comments');
  await expect(thread.getByText(body)).toBeVisible();

  // A reload proves it reached content-service rather than only the local thread state. The thread
  // defaults to Top and reveals the first batch only, so a brand-new comment with no likes sits
  // below the fold — sort by Newest to bring it back.
  await page.reload();
  await thread.getByRole('button', { name: 'Top' }).click();
  await page.getByRole('menuitem', { name: 'Newest' }).click();
  await expect(thread.getByText(body)).toBeVisible();
});
