spring.application.name=content-service
server.port=8082
management.endpoints.web.exposure.include=health

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/contentdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.user-service-base-url=${USER_SERVICE_BASE_URL:http://localhost:8081}
app.genai-service-base-url=${GENAI_SERVICE_BASE_URL:http://localhost:8000}

