spring.application.name=recommendation-service
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:verita_users}
spring.datasource.username=${DB_USER:verita_user}
spring.datasource.password=${DB_PASSWORD:verita_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8083
management.endpoints.web.exposure.include=health
