apiVersion: v2
name: verita
description: Umbrella Helm chart for the Verita platform
type: application
version: 0.2.0
appVersion: "0.1.0"

dependencies:
  - name: postgresql
    version: 18.4.0
    repository: https://charts.bitnami.com/bitnami
    alias: user-postgresql
    condition: userPostgresql.enabled
  - name: postgresql
    version: 18.4.0
    repository: https://charts.bitnami.com/bitnami
    alias: content-postgresql
    condition: contentPostgresql.enabled
  - name: postgresql
    version: 18.4.0
    repository: https://charts.bitnami.com/bitnami
    alias: recommendation-postgresql
    condition: recommendationPostgresql.enabled
