global:
  registry: registry.example.com
  imagePullSecrets: []
content:
  replicaCount: 1
  image:
    repository: verita/content
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8082
user:
  replicaCount: 1
  image:
    repository: verita/user
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8081
recommendation:
  replicaCount: 1
  image:
    repository: verita/recommendation
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8083
genai:
  replicaCount: 1
  image:
    repository: verita/genai
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
frontend:
  replicaCount: 1
  image:
    repository: verita/frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
ingress:
  enabled: true
  host: example.k8s.ase.cit.tum.de
  tls:
    secretName: verita-tls
