global:
  registry: ghcr.io/aet-devops26/team-colleague-md
  imagePullSecrets: []

content:
  replicaCount: 1
  image:
    repository: content-service
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8082

user:
  replicaCount: 1
  image:
    repository: user-service
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8081

recommendation:
  replicaCount: 1
  image:
    repository: recommendation-service
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8083

genai:
  replicaCount: 1
  image:
    repository: genai-service
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8000

frontend:
  replicaCount: 1
  image:
    repository: frontend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80

ingress:
  enabled: true
  host: verita.stud.k8s.aet.cit.tum.de
  tls:
    secretName: verita-tls

resources:
  requests:
    cpu: "50m"
    memory: "32Mi"
  limits:
    cpu: "500m"
    memory: "128Mi"