global:
  registry: registry.example.com
  imagePullSecrets: []
content:
  replicaCount: 1
  image:
    repository: verita/content
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8082
user:
  replicaCount: 1
  image:
    repository: verita/user
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8081
recommendation:
  replicaCount: 1
  image:
    repository: verita/recommendation
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8083
genai:
  replicaCount: 1
  image:
    repository: verita/genai
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
frontend:
  replicaCount: 1
  image:
    repository: verita/frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
ingress:
  enabled: true
  host: verita.k8s.ase.cit.tum.de
  tls:
    secretName: verita-tls

userPostgresql:
  enabled: true
  auth:
    username: user_service
    password: change-me-user
    database: userdb
  primary:
    persistence:
      enabled: true
      size: 8Gi

contentPostgresql:
  enabled: true
  auth:
    username: content_service
    password: change-me-content #TODO auth.exportingSecret
    database: contentdb
  primary:
    persistence:
      enabled: true
      size: 8Gi

recommendationPostgresql:
  enabled: true
  auth:
    username: recommendation_service
    password: change-me-recommendation
    database: recommendationdb
  primary:
    persistence:
      enabled: true
      size: 8Gi

