import { useState } from 'react';
import type { SummaryStatus } from '../../../types';
import { timeAgo } from '../../../utils/timeAgo';
import styles from './AISummaryPanel.module.css';

interface AISummaryPanelProps {
  status: SummaryStatus;
  summary?: string | null;
  generatedAt?: string | null;
  model?: string | null;
}

function summaryBullets(summary?: string | null): string[] {
  return (summary ?? '')
    .split('\n')
    .map((line) => line.replace(/^[\s]*[•\-*]\s*/, '').trim())
    .filter(Boolean);
}

export default function AISummaryPanel({ status, summary, generatedAt, model }: AISummaryPanelProps) {
  const [open, setOpen] = useState(false);
  const bullets = summaryBullets(summary);
  const isUpdating = status === 'PENDING' && bullets.length > 0;
  const isGenerating = status === 'PENDING' && bullets.length === 0;
  const generatedLabel = generatedAt ? `generated · ${timeAgo(generatedAt)}` : null;

  if (status === 'FAILED' || status === 'NONE' || (status === 'COMPLETED' && bullets.length === 0)) {
    return null;
  }

  return (
    <>
      <button
        className={`${styles.toggle} ${open ? styles.toggleOpen : ''}`}
        onClick={() => setOpen((o) => !o)}
        aria-expanded={open}
        type="button"
      >
        <svg className={styles.spark} width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
          <path d="M12 3v3M12 18v3M3 12h3M18 12h3M5.6 5.6l2.1 2.1M16.3 16.3l2.1 2.1M5.6 18.4l2.1-2.1M16.3 7.7l2.1-2.1" />
        </svg>
        <span>AI summary</span>
        <svg className={`${styles.chev} ${open ? styles.chevOpen : ''}`} width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round">
          <path d="m6 9 6 6 6-6" />
        </svg>
      </button>

      <div className={`${styles.panelWrap} ${open ? styles.panelWrapOpen : ''}`} aria-hidden={!open}>
        <div className={styles.panel}>
          <div className={styles.panelHeader}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
              <path d="M12 3v3M12 18v3M3 12h3M18 12h3M5.6 5.6l2.1 2.1M16.3 16.3l2.1 2.1M5.6 18.4l2.1-2.1M16.3 7.7l2.1-2.1" />
            </svg>
            <span className={styles.panelLabel}>Key points</span>
            {isUpdating && <span className={styles.updatingTag}>updating</span>}
            {generatedLabel && <span className={styles.panelTag}>{generatedLabel}</span>}
          </div>

          {isGenerating ? (
            <div className={styles.pending}>
              <div className={styles.skeletonLine} />
              <div className={styles.skeletonLineShort} />
              <p>AI is generating summary...</p>
            </div>
          ) : (
            <ul className={styles.bullets}>
              {bullets.map((bullet, i) => (
                <li key={i}>{bullet}</li>
              ))}
            </ul>
          )}

          {model && <div className={styles.panelFoot}>Generated by {model}</div>}
        </div>
      </div>
    </>
  );
}
